version: "3.8"
services:
  postgres-db:
    container_name: FoodEntry
    image: postgres # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: foodentry_dev
      POSTGRES_PASSWORD: foodentry_dev
      POSTGRES_DB: foodentry
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5436:5432"

volumes:
  postgresql_data:
    driver: local