CREATE TABLE bucketlist_items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255),
    is_complete BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_bucketlist_items PRIMARY KEY (id)
);