CREATE TABLE food_entry
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    date            VARCHAR(255),
    qty             DOUBLE PRECISION                        NOT NULL,
    macrosentity_id BIGINT,
    user_id         BIGINT,
    CONSTRAINT pk_foodentry PRIMARY KEY (id)
);

CREATE TABLE macros_entity
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    calories INTEGER                                 NOT NULL,
    protein  DOUBLE PRECISION                        NOT NULL,
    carbs    DOUBLE PRECISION                        NOT NULL,
    fat      DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_macrosentity PRIMARY KEY (id)
);

CREATE TABLE user_entity
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    age      INTEGER                                 NOT NULL,
    CONSTRAINT pk_userentity PRIMARY KEY (id)
);

ALTER TABLE food_entry
    ADD CONSTRAINT uc_foodentry_macrosentity UNIQUE (macrosentity_id);

ALTER TABLE food_entry
    ADD CONSTRAINT FK_FOODENTRY_ON_MACROSENTITY FOREIGN KEY (macrosentity_id) REFERENCES macros_entity (id);

ALTER TABLE food_entry
    ADD CONSTRAINT FK_FOODENTRY_ON_USER FOREIGN KEY (user_id) REFERENCES user_entity (id);